return {
  -- "srcery-colors/srcery-vim",
  "olimorris/onedarkpro.nvim",
  "Mofiqul/vscode.nvim",
  "LunarVim/darkplus.nvim",
  "arkav/lualine-lsp-progress",
  "projekt0n/github-nvim-theme",
  "yazeed1s/oh-lucy.nvim",
  "Everblush/nvim",
  "AlexvZyl/nordic.nvim",
  "Tsuzat/NeoSolarized.nvim",
  "catppuccin/nvim",
  "rebelot/kanagawa.nvim",
  "EdenEast/nightfox.nvim",
  "sekke276/dark_flat.nvim",
}
